# Generated by Django 5.1.4 on 2025-01-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='draw',
            table='lotto_draw',
        ),
    ]
