# Python 3.10 이미지를 사용
FROM python:3.10-slim

# 작업 디렉토리 설정
WORKDIR /app

# Pip3 업데이트 및 의존성 설치
COPY requirements.txt .
RUN pip3 install --upgrade pip && pip3 install --no-cache-dir -r requirements.txt

# 프로젝트 파일 복사
COPY . .

# Django 서버 실행
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
